### ISSUE TITLE
Heartbeat Recovery?

### ISSUE THREAD

**Issue by Aubron** [TheZ3ro/pkmngo-map#2] opened 2016-07-19 14:54 UTC
### Environment info
Operating System: Ubuntu

Installed version of Python: 2.7.6

### Steps to reproduce
1. Fail Heartbeat

On a heartbeat fail, script never seems to recover. Just keeps missing heartbeat indefinitely. Script can be restarted and immediately resume, so currently that is preferable. Need to either restart script at a higher level on heartbeat fail, or ascertain why recovery is currently not instant.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

[+] Found pokemon!
    (19) Rattata
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying
[-] Heartbeat missed, retrying

**Comment by TheZ3ro** [comment] 2016-07-19 16:15
Actually there is Heartbeat rescue code https://github.com/TheZ3ro/pkmngo-map/blob/maps/main.py#L354

How do you manually fail the heartbeat? Do you cut off your internet connection for a while?

**Comment by Aubron** [comment] 2016-07-19 17:10
I'm referring to the fact that this is how my script always ends, if I leave this script running for an hour or more I will always return to it being stuck on 'Heartbeat missed, retrying'. The script typically has to be restarted to recover from this error.

**Comment by minthat** [comment] 2016-07-19 19:26
Known Issue, from MemeLyfe code:
https://github.com/memelyfe/pokemongo-api-demo/issues/4

Here is the current Heartbeat code:


```
def raw_heartbeat(api_endpoint, access_token, response):
    m4 = pokemon_pb2.RequestEnvelop.Requests()
    m = pokemon_pb2.RequestEnvelop.MessageSingleInt()
    m.f1 = int(time.time() * 1000)
    m4.message = m.SerializeToString()
    m5 = pokemon_pb2.RequestEnvelop.Requests()
    m = pokemon_pb2.RequestEnvelop.MessageSingleString()
    m.bytes = "05daf51635c82611d1aac95c0b051d3ec088a930"
    m5.message = m.SerializeToString()

    walk = sorted(getNeighbors())

    m1 = pokemon_pb2.RequestEnvelop.Requests()
    m1.type = 106
    m = pokemon_pb2.RequestEnvelop.MessageQuad()
    m.f1 = ''.join(map(encode, walk))
    m.f2 = "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
    m.lat = COORDS_LATITUDE
    m.long = COORDS_LONGITUDE
    m1.message = m.SerializeToString()
    response = get_profile(
        access_token,
        api_endpoint,
        response.unknown7,
        m1,
        pokemon_pb2.RequestEnvelop.Requests(),
        m4,
        pokemon_pb2.RequestEnvelop.Requests(),
        m5)
    payload = response.payload[0]
    heartbeat = pokemon_pb2.ResponseEnvelop.HeartbeatPayload()
    heartbeat.ParseFromString(payload)
    return heartbeat

def heartbeat(api_endpoint, access_token, response):
    while True:
        try:
            h = raw_heartbeat(api_endpoint, access_token, response)
            return h
        except Exception, e:
            if DEBUG:
                print(e)
            print('[-] Heartbeat missed, retrying')
```

Step 1 is to figure out why the heartbeat fails (raw_heartbeat). Is the PGO server ending sessions that aren't active (moving around)? If so, you could add a minor walking distance to the script so that the location moves around. If there isn't a way to find out what's causing the session to timeout or if the cause is not something that can be fixed, consider adding a quick attempts clause to heartbeat so that it restarts the necessary portions of the script (like login?), no need to have the whole damn thing restart! Something along these lines, I'm guessing:

```
Attempts = 0
while attempts < 3:
    try:
        #heartbeat_raw code
        break
    except Exception, e:
            if DEBUG:
                attempts += 1
                print(e)
            print('[-] Heartbeat missed, retrying')

while attempts = 3:
  #create new session
  attempts == 0
```

**Comment by minthat** [comment] 2016-07-20 17:17
Hey xero, just wanted to add, the issue presents itself exactly 30 minutes after starting the script 100% of the time.  The rescue code won't work where it's at (if it were actually enabled to do something other than spam 'error' , because the session needs to be revalidated. Only way for it to be restored is to break out of main and restart it (or just run the login part again?).

**Comment by TheZ3ro** [comment] 2016-07-20 17:51
Yes, I think we need to refresh the session token. I will dive into this in the next few days.

Thanks for all your help in other issues as well!

**Comment by minthat** [comment] 2016-07-20 18:57
No problem, I'm not really a dev, but I'm working on a (probably dirty?) solution to this. Will update if I have any luck.

**Comment by minthat** [comment] 2016-07-20 19:46
OK, so I think I fixed it by adding the variable
`is_valid = True`
and then adding
`is_valid = False` 
to the heartbeat rescue code and
`while True:`
to the beginning of main and
`while is_valid==True`
in front of 
`scan(api_endpoint, access_token, response, origin, pokemons)`

I watched it rescue itself a couple times, but then the servers went down so....I THINK it works?

**Comment by minthat** [comment] 2016-07-20 20:42
Check out the edits here:

https://github.com/minthat/P-Go-Dev-Don-t-use-/blob/master/main.py

**Comment by TheZ3ro** [comment] 2016-07-21 16:44
I'm reading your code right now.

It's not based on my fork anyway, I will try to merge the change :wink:

**Comment by TheZ3ro** [comment] 2016-07-21 17:50
Fixed in https://github.com/TheZ3ro/pkmngo-map/commit/3745c14b3b44ec2d4bc9d23fb7d55252586b9fa6

**Closed by TheZ3ro** 2016-07-21 17:50 UTC
